In [1]:
import numpy as np

In [2]:
# numpy.ndarray
x = np.array([1.0,2.0,3.0]);print(x)

[ 1.  2.  3.]


In [3]:
type(x)

numpy.ndarray

In [4]:
y = x*2;print(y)# broadcasting

[ 2.  4.  6.]


In [5]:
x + y

array([ 3.,  6.,  9.])

In [6]:
x * y

array([  2.,   8.,  18.])

In [7]:
x / y

array([ 0.5,  0.5,  0.5])

In [8]:
A = np.array([[1,2],[3,4]])

In [9]:
print(A)
print(A.shape)
print(A.dtype)

[[1 2]
 [3 4]]
(2, 2)
int32


In [10]:
B = np.array([[3,0],[0,6]]);B

array([[3, 0],
       [0, 6]])

In [11]:
A * B # element-wise product

array([[ 3,  0],
       [ 0, 24]])

In [12]:
np.dot(A,B) # matrix product

array([[ 3, 12],
       [ 9, 24]])

In [13]:
C = np.array([10,20]);D = np.array([[10],[20]]) 
print(C)
print(D)

[10 20]
[[10]
 [20]]


In [14]:
def product(A,B):
    print("A = ");print(A)
    print("B = ");print(B)
    print("A * B = ");print(A * B)

In [15]:
product(A,C)
product(A,D)

A = 
[[1 2]
 [3 4]]
B = 
[10 20]
A * B = 
[[10 40]
 [30 80]]
A = 
[[1 2]
 [3 4]]
B = 
[[10]
 [20]]
A * B = 
[[10 20]
 [60 80]]


In [16]:
X = np.array([[[1,2],[3,4]],[[-1,-2],[-3,-4]]]);X
Xf=X.flatten();Xf
Xmat = Xf.reshape(2,2,2);Xmat

array([[[ 1,  2],
        [ 3,  4]],

       [[-1, -2],
        [-3, -4]]])

In [17]:
np.dot(X,X)

array([[[[  7,  10],
         [ -7, -10]],

        [[ 15,  22],
         [-15, -22]]],


       [[[ -7, -10],
         [  7,  10]],

        [[-15, -22],
         [ 15,  22]]]])

In [18]:
X > 2 ;X[X > 2]

array([3, 4])